### ISSUE TITLE
Update documentation for orchestration tools without edit state

### ISSUE THREAD

**Issue by janmichek** [keboola/connection-docs#107]
Az bude v produkci 
https://github.com/keboola/kbc-ui/pull/2457
https://github.com/keboola/kbc-ui/pull/2433
https://github.com/keboola/kbc-ui/pull/2428

bude potreba upravit screeny a pripadne textovy navod.

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/connection-docs/commit/6b7ce5b81232cd6cf6fada3d81a20e9099c33862
