### ISSUE TITLE
incremental fetching

### ISSUE THREAD

**Issue by odinuv** [keboola/connection-docs#109]

**Comment by ondrejhlavacek** [comment]
@odinuv co to má bejt? není to https://help.keboola.com/storage/tables/#incremental-processing?

**Comment by odinuv** [comment]
ne to je u db extractoru

**Comment by pivnicek** [comment]
@odinuv shall I put this together quickly?

**Comment by odinuv** [comment]
https://i.kym-cdn.com/photos/images/original/000/066/016/keep-calm-and-carry-on-original.jpg

**Comment by odinuv** [comment]
https://keboola.atlassian.net/jira/software/projects/DOC/boards/15?selectedIssue=DOC-3
