### ISSUE TITLE
Consider including also some "low level" options for GoodData Writer

### ISSUE THREAD

**Issue by ujovlado** [keboola/connection-docs#136]
Marcus wrote in ticket:

> I think it's important to link the github into the component description no matter what. these are pretty key things to know and that needs to be replaced in the orchestrator for many clients. so these parameters are things that everyone needs.

He speaks about:

> loadOnly - skip model update, just load data

> multiLoad - flag if the tables should be integrated one by one or all at once (may be good for some situations, see https://help.gooddata.com/display/developer/Multiload+of+CSV+Data)

^ mentioned options are available only in component's repo https://github.com/keboola/gooddata-writer-v3

**Comment by ujovlado** [comment]
Zalozil som to sem, lebo si mysli, ze ked uz, tak to ma byt v dokumentacii. Imho nechceme na stranke komponenty otravovat usera s takymito vecami.

**Comment by ujovlado** [comment]
https://keboola.zendesk.com/agent/tickets/10150

**Comment by odinuv** [comment]
https://keboola.atlassian.net/jira/software/projects/DOC/boards/15?selectedIssue=DOC-13
