### ISSUE TITLE
Automate component's configuration docs

### ISSUE THREAD

**Issue by ujovlado** [keboola/connection-docs#143]
Related to https://github.com/keboola/kbc-ui/pull/3164

@natocTo myslim, ze do dokumentacie si este nic nepridaval, tak by bolo fajn si to vyskusat. :)

**Comment by natocTo** [comment]
Pokouším se rozjet tu dokumentaci, ale nedaří se mi.

Když dám `docker-compose run --rm --service-ports jekyll`
A pak jdu na `http://localhost:4000/`
Tak vidím jen jako directory tree nebo jak to napsat, ještě prázdnou. Dokumentace mi nenaběhne.

Ještě jsem se chtěl podívat na ten odkaz co je v Readme. A ten mi taky nefunguje.

Je nějaký jiný postup pro Windows jak to rozjet nebo je stejné, jen dělám něco špatně?
