### ISSUE TITLE
Organization settings - Multi-Factor Authentication

### ISSUE THREAD

**Issue by ErikZigo** [keboola/connection-docs#148]
![image](https://user-images.githubusercontent.com/1726727/56949347-f1c0ec00-6b32-11e9-9ac4-6aed427bc508.png)

Pokud je volba zapnutá tak všichni uživatelé v organizaci a jejích projektech musí mít zaplé MFA.

**Comment by odinuv** [comment]
https://keboola.atlassian.net/jira/software/projects/DOC/boards/15?selectedIssue=DOC-12
