### ISSUE TITLE
working with sliced files --> add to help.keboola.com

### ISSUE THREAD

**Issue by mwong023** [keboola/connection-docs#15]
hey support,

I expected to find the documentation for working with sliced files within help.keboola.com, only to realize it's in developers.keboola.com.  (https://developers.keboola.com/integrate/storage/api/import-export/)

i think it should be in help.keboola.com as well because those files are being (or can be) downloaded from the UI ... since our customers are users of KBC and need access to these files ... it should be in help.keboola.com i guess (rather than having to find it in a different place).

**Comment by mwong023** [comment]
hmm ... well just because it is "strong stuff" doesn't mean that it has to belong to developers right?

Our office always sells KBC as selling the data platform as a service, so you do not have to worry about things such as data audits or file audits.  Checking tables that were imported or exported during a specific event is quite a routine task for me, and is kind of a "big deal" to the platform. 

There is nothing about the files being sliced that is about "development" of the platform.  It is part of the UI functionality and it requires some shitty work to merge the sliced files, but it is not building on top of the platform.  so i still think it should be in help.keboola.com :)

**Comment by Halama** [comment]
Hi marcus,
there will be "auto-merging" when you will be downloading sliced files from ui.

**Comment by odinuv** [comment]
fixed in UI
