### ISSUE TITLE
Note about MongoDB skipping "invalid" documents in some cases

### ISSUE THREAD

**Issue by ujovlado** [keboola/connection-docs#150]

**Comment by ujovlado** [comment]
odpalim to rovno s https://github.com/keboola/connection-docs/issues/164

**Comment by odinuv** [comment]
@ujovlado asi to budes muset odpalit zvlast, ja bohuzel nevim co jsou "some cases"

**Comment by ujovlado** [comment]
poriesim asap, popri to Authentication Database asi nevydalo :)

**Comment by odinuv** [comment]
https://keboola.atlassian.net/jira/software/projects/DOC/boards/15?selectedIssue=DOC-6
