### ISSUE TITLE
What about Bing Ads ?

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [keboola/connection-docs#151]
There is a bullet point without link on https://help.keboola.com/extractors/marketing-sales/ 

Where do you stand with Bing Ads ?

**Comment by odinuv** [comment]
Hello,
not every component has(/needs) a separate documentation page. Also the BingAds extractor is a 3rd party component, so it has the documentation provided by it's author and available inside Keboola Connection app. Is there any specific information you're looking for?

**Comment by googleanalyticsresoneo** [comment]
Hi,

Let's say it's difficult to have a precise and exhaustive view on the connectors that are available.
Where is the right place to look at ?

Then documentation mentioning something without a link look either obsolete, or incomplete, or who knows... just planned ? drop ?

Links can go to third party pages, no ? I believe it's an Internet feature that remains :-) 

I hope that makes sense

My Best

**Comment by odinuv** [comment]
Yes, it makes sense, will fix this!

The life list of available public components is at https://components.keboola.com/components

**Comment by googleanalyticsresoneo** [comment]
incredible list ! couldn't find it by myself ! too bad

thanks for your attention !

**Comment by odinuv** [comment]
fixed, if you run into anything else, let us know
