### ISSUE TITLE
Email attachments documentation inacurrate

### ISSUE THREAD

**Issue by davidesner** [keboola/connection-docs#161]
The email attachments documentation is unclear on how it behaves.

1) It says attachments may be gzipped. They can't. When it contains gzipped attachment, the attachment is not recognized.
2) It is not clear that you cannot have multiple attachments in the same email
![image](https://user-images.githubusercontent.com/15654252/62683314-67541800-b9be-11e9-8abe-03c5867cb1e3.png)

3) It is not clear that when you send multiple emails with attachments and then load them it will create multiple output tables, even though the attachment name is the same or the subject names are the same.

![image](https://user-images.githubusercontent.com/15654252/62682972-b0579c80-b9bd-11e9-8f74-bdaef184ac80.png)

**Comment by odinuv** [comment]
fixed in terms of the docs accuracy, but the email attachment ex definitely needs some work
