### ISSUE TITLE
update gd writer docs

### ISSUE THREAD

**Issue by odinuv** [keboola/connection-docs#178]
https://help.keboola.com/writers/bi-tools/gooddata/
and 
https://help.keboola.com/tutorial/write/gooddata/

**Comment by JakubMatejka** [comment]
@odinuv ten tutorial mám celý přescreenshotovat i včetně těch transformací? Asi jo, co? (je to ve starým designu)

**Comment by odinuv** [comment]
nevim jestli s tim nepockat na novy UI, je to prace pro vraha :/ 
na druhou stranu jak je to takhle tak by bylo skoro lepsi to tam nemit

**Comment by JakubMatejka** [comment]
;o) Já to pro tu jednu stránku teď klidně udělám. Přijde mi divný to mít v rámci stránky na jednom screenshotu po staru a na druhým po novu. U tý stránky na bi-tools jsem je upravil taky, protože tam jsou některý věci jinak: https://github.com/keboola/connection-docs/pull/180/files Ale vlastně teď nevím jestli by se to nemělo s novým ui updatnout najednou? (No jo, ale ono vlastně nový ui bude za měsíc ještě úplně nový, tak to bude vypadat zas trochu jinak. 🤔 )

**Comment by odinuv** [comment]
no s novym ui se to urcite updatovat bude, ale jestli teda ses ochotnej to udelat, tak to asi radsi udelej hned, at tu nemame kraviny
