### ISSUE TITLE
define structure

### ISSUE THREAD

**Issue by Halama** [keboola/connection-docs#2]

**Comment by odinuv** [comment]
Level 0:
User Space (předpoklad je, že je to člověk, který umí klikat a případně umí SQL (nebo R)
Devel Space (předpoklad je, že je to člověk, který umí posílat API requesty, bash, nebo nějaký programovací jazyk)

Mohly by to být i oddělené domény - něco jako:
help.keboola.com
a devhelp.keboola.com


User space :
---------------

- Introduction
- Keboola Mission, Open, no vendor lock in, takeout
  - Glossary (extractor, orchestrator, writer, token, credentials)
  - Tutorial (GettingStarted) tak proklikat to odsud sem, aby to lame pomohlo v zakladni orientaci v UI, mozna screen cast
  - Environment/Ecosystem (Partners)
- Loading data
  - introduction (goal, limits, sources)
  - extractors
    - facebook ads
    - generic extractor
    - ...
  - manual import (CSV requirements)
- Storage
  - backends (billing plans)
  - buckets and tables
  - file uploads
  - API (odkaz na develspace)
- Manipulating data
  - transformations
    - SQL transformations
      - Mysql
      - Redshift
      - Snowflake
    - R transgormations
  - applications
- Writing/Consuming data
  - writers
    - gd writer
    - tableau writer
    - ...
- Automation
  - orchestrator 
    - chained transformations
    - using applications
  - watchdog
- Administration
  - login methods (MFA, google login, tokens)
  - organization managemet
    - token management
    - user management
  - notifications
  - project management
    - project backup
    - data takeout
- Tips & tricks
  - Link to Wiki
  - ... ?



Devel space:
-----------------

- Integrate KBC 
  - Using API
  - Storage
    - API
    - Curl
    - Commandline
  - Transformation
    - API
    - IO Mapping
    - Sandbox
  - Extractors
    - Mailchimp
    - App Annie
    - ...
  - Writers
- Extend KBC (3rd party functionality)
  - Generic extractor
  - Custom applications
  - Docker components
- Automation/Common tasks
  - Load data from your system
  - Trigger orchestrations
  - Send data
  - Copy buckets from different projects

**Comment by odinuv** [comment]
merged in a8b02b07eecbc223142c8f86e0d4bd7f9e09647d
