### ISSUE TITLE
BYODB

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/connection-docs#27]
https://keboola.slack.com/archives/C0A5ZK1LY/p1489350350606000

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C02CMFLDG/p1491557250232700

**Comment by odinuv** [comment]
https://github.com/keboola/connection-docs/pull/28

**Comment by odinuv** [comment]
readabe link: https://github.com/keboola/connection-docs/blob/byodb/storage/byodb.md

**Comment by ondrejhlavacek** [comment]
![connection-docs_byodb_md_at_byodb_ _keboola_connection-docs](https://cloud.githubusercontent.com/assets/497675/24847390/ea2c8132-1dc0-11e7-86f3-c40efed9e9c9.png)

Ten první (+ druhej) odstavec se mi nějak nezdá. Zkusil bych je sjednotit... něco jako

Keboola Connection Storage provisions resources required for storing all of your business data (table contents and file uploads). However, if you eg. already use a Redshift or a Snowflake database or you want to use them for other purposes as well, then you might want to use your own database with KBC.

**Comment by ondrejhlavacek** [comment]
Pro začátek to imho stačí, pak bych tam někdy doplnil výhody + nevýhody a nějaký popis toho, co my na těch resourcech budeme cca dělat...

**Comment by odinuv** [comment]
Fixed in https://github.com/keboola/connection-docs/commit/15dc4c98ca73f54cc8ceb113350f0fef0b687e5a
