### ISSUE TITLE
Transformations clarification

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/connection-docs#30]
https://www.evernote.com/l/AA0DwGB63c5E_LCFHG3OsIlNd9lb2GJeCmw

---

Hi Marcus,

I think it is quite clear if your read the whole context around. A table references a database transformation, file R/Python/OpenRefine. The docs say: This data is made available as a table for SQL, or as a CSV file for R and Python.

Does it make sense?

---
well, after you point that out i guess so.

but if I'm reading it from a position of complete KBC newbie, i don't think that is very clear. even in your explanation there, you highlighted the words "table" and "file" ... so even you thought it required extra emphasis (or extra explanation).

Perhaps it's written accurately. but as we are demo'ing customers, it seems that this area is an area they are not super clear on what's going on (what is mapping, etc), so i was re-looking over the docs to see if we can improve it or describe it in the best way.

![pasted image at 2017_05_27 06_54 am](https://cloud.githubusercontent.com/assets/497675/26529350/c63a5d16-43be-11e7-9aa6-9152f681f31d.png)

---

To be honest I think ppl get confused for a bit that the table gets put into a separate DB ... so the whole mapping thing gets confusing because before u understand mapping, u have to understand on a more macro level what the hell transformations are doing.      Maybe a summary of what's happening would help. I think a diagram similar to attached, summarizes the four essential parts of transformations.      The four parts are, Storage, transformation DB, mappings, and queries.

![img_5725](https://cloud.githubusercontent.com/assets/497675/26529358/f4b630c0-43be-11e7-8a3d-ca5385f58a89.JPG)

**Comment by odinuv** [comment]
@ondrejhlavacek  https://help.keboola.com/manipulation/transformations/#overview ?

**Comment by odinuv** [comment]
more or less done in 952ffeac1521483aa84405620158e925429834f1
