### ISSUE TITLE
Nepodareny merge

### ISSUE THREAD

**Issue by ujovlado** [keboola/connection-docs#36]
https://help.keboola.com/manipulation/transformations/

**Comment by ujovlado** [comment]
![screenshot_2017-07-17_16-50-00](https://user-images.githubusercontent.com/419849/28274011-013ca34c-6b10-11e7-86e5-dd7f367a04a6.png)

**Comment by odinuv** [comment]
@ondrejhlavacek spravil bys to? ja uz mam zmatek v tom co tam ma byt a nema byt

**Comment by ondrejhlavacek** [comment]
shit! díkec! to mi muselo nějak debilně utýct :-(
