### ISSUE TITLE
Project Invitations

### ISSUE THREAD

**Issue by ErikZigo** [keboola/connection-docs#89]
Describe new workflow in inviting users to project
https://help.keboola.com/management/project/users/#inviting-a-user

**Comment by Halama** [comment]
Hodil bych tam i tu tabulku oprávnění:

![image](https://user-images.githubusercontent.com/1726727/47808174-17b13380-dd3e-11e8-8d7c-d911d3dfad47.png)

**Comment by odinuv** [comment]
@ErikZigo mas to rozdelany, nebo to mam udelat? (klidne to udelam, ptam se at to nedelame 2x)

**Comment by ErikZigo** [comment]
@odinuv Ty mas na to volno? To by bylo super kdyby to mohl napsat nekdo jiny nez ja jako autor. Protoze ja chapu jak to funguje diky tomu ze jsem to naprogramoval. Nejsem si ale jisty jestli z meho popisu by to pochopil BFU.

Jeste jsem se k tomu nedostal, puvodne jsem to mel v planu ze dneska na to kouknu.

**Comment by odinuv** [comment]
jj, mam. ok, beru si to

**Comment by ErikZigo** [comment]
Kazdopadne s dotazy jsem k dispozici

**Comment by odinuv** [comment]
done in 858133817d525a0bbcef8d0e92a8d31146e5ce3b
