### ISSUE TITLE
add validation info

### ISSUE THREAD

**Issue by janmichek** [keboola/connection-docs#99]
https://github.com/keboola/kbc-ui/pull/2028#issuecomment-432158624
Pridat vetu 'Tables defined in Output Mapping that does not yet exist in Storage are not validated.'
Nejspise umistit sem https://help.keboola.com/manipulation/transformations/

**Comment by odinuv** [comment]
waits for backend release

**Comment by odinuv** [comment]
https://keboola.atlassian.net/jira/software/projects/DOC/boards/15?selectedIssue=DOC-8
